---
engines:
  csslint:
    enabled: true
  scss-lint:
    enabled: true
  markdownlint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.scss"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
  - "**.png"
  - "**.jpg"
  - "**.gif"
  - "gulpfile.js"
  - "composer.lock"
  - "phpcs.xml"
  - "**.json"
  - "**.pot"
  - "**.txt"
  - "**-min.js"
  - "**-min.css"
  - "**.dist"
  - "**.sh"
